schema_version: 1

context:
  version: "4.8.5"

package:
  name: cedarpy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cedarpy/cedarpy-${{ version }}.tar.gz
  sha256: 29caffc957030b515f4c6e7caebd9bb870877c08d8cabc82a9d0664aeaa14761

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - python
    - maturin >=1.8,<2
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - cedarpy
      pip_check: true

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/cedarpy/
  repository: https://github.com/k9securityio/cedar-py
  summary: Python bindings for the Cedar Policy project.

extra:
  recipe-maintainers:
    - xhochy
    - swenger
